class AppText {
  static final Map<String, Map<String, String>> _text = {
    'th': {
      'appName': 'Modern Shop',
      'login': 'เข้าสู่ระบบ',
      'register': 'สมัครสมาชิก',
      'noAccount': 'ยังไม่มีบัญชี? สมัครสมาชิก',
      'haveAccount': 'มีบัญชีแล้ว? กลับไปเข้าสู่ระบบ',
      'username': 'ชื่อผู้ใช้',
      'password': 'รหัสผ่าน',
      'confirmPassword': 'ยืนยันรหัสผ่าน',
      'luxuryExperience': 'ประสบการณ์ช้อปปิ้งระดับพรีเมียม',
      'home': 'หน้าหลัก',
      'logout': 'ออกจากระบบ',
      'wishlist': 'สินค้าที่ชอบ',
      'cart': 'ตะกร้าสินค้า',
      'searchHint': 'ค้นหาสินค้า หรือ หมวดหมู่',
      'luxuryCollection': 'คอลเลกชันพรีเมียม',
      'luxuryDescription':
          'ช้อปปิ้งในสไตล์พรีเมียม พร้อมดีไซน์หรูหราและประสบการณ์ที่เหนือระดับ',
      'premiumExperience': 'ประสบการณ์พรีเมียม',
      'featuredCollection': 'สินค้ายอดนิยม',
      'featuredSubtitle': 'สินค้าเด่นในลุคพรีเมียม',
      'allProducts': 'สินค้าทั้งหมด',
      'allProductsSubtitle': 'ค้นหา กรองหมวดหมู่ เพิ่ม แก้ไข และลบสินค้า',
      'addProduct': 'เพิ่มสินค้า',
      'editProduct': 'แก้ไขสินค้า',
      'deleteProduct': 'ลบสินค้า',
      'productDetail': 'รายละเอียดสินค้า',
      'premiumProduct': 'สินค้าพรีเมียม',
      'rating': 'คะแนน',
      'reviews': 'รีวิว',
      'description': 'รายละเอียดสินค้า',
      'addToCart': 'เพิ่มลงตะกร้า',
      'addedToCart': 'เพิ่มสินค้าลงตะกร้าแล้ว',
      'shoppingBag': 'ตะกร้าสินค้า',
      'emptyCart': 'ยังไม่มีสินค้าในตะกร้า',
      'totalPayment': 'ยอดรวมทั้งหมด',
      'checkout': 'ชำระเงิน',
      'proceedCheckout': 'ไปชำระเงิน',
      'paymentMethod': 'วิธีชำระเงิน',
      'orderSummary': 'สรุปคำสั่งซื้อ',
      'totalItems': 'จำนวนสินค้าทั้งหมด',
      'confirmPayment': 'ยืนยันการชำระเงิน',
      'paymentSuccess': 'ชำระเงินสำเร็จ',
      'orderSuccessful': 'สั่งซื้อสำเร็จ',
      'thankYou': 'ขอบคุณสำหรับการสั่งซื้อสินค้า',
      'backHome': 'กลับหน้าหลัก',
      'clear': 'ล้างทั้งหมด',
      'noFavorite': 'ยังไม่มีสินค้าที่ชอบ',
      'language': 'ภาษา',
      'thai': 'ไทย',
      'english': 'English',
      'all': 'ทั้งหมด',
      'electronics': 'อิเล็กทรอนิกส์',
      'jewelery': 'เครื่องประดับ',
      "men's clothing": 'เสื้อผ้าผู้ชาย',
      "women's clothing": 'เสื้อผ้าผู้หญิง',
    },
    'en': {
      'appName': 'Modern Shop',
      'login': 'Login',
      'register': 'Register',
      'noAccount': 'No account? Register',
      'haveAccount': 'Already have an account? Back to Login',
      'username': 'Username',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'luxuryExperience': 'Luxury Shopping Experience',
      'home': 'Home',
      'logout': 'Logout',
      'wishlist': 'Wishlist',
      'cart': 'Cart',
      'searchHint': 'Search product or category',
      'luxuryCollection': 'Luxury Collection',
      'luxuryDescription':
          'Premium shopping with elegant design and a superior experience',
      'premiumExperience': 'Premium Experience',
      'featuredCollection': 'Featured Collection',
      'featuredSubtitle': 'Premium selected products',
      'allProducts': 'All Products',
      'allProductsSubtitle': 'Search, filter, add, edit and delete products',
      'addProduct': 'Add Product',
      'editProduct': 'Edit Product',
      'deleteProduct': 'Delete Product',
      'productDetail': 'Product Detail',
      'premiumProduct': 'Premium Product',
      'rating': 'Rating',
      'reviews': 'reviews',
      'description': 'Description',
      'addToCart': 'Add to Cart',
      'addedToCart': 'Product added to cart',
      'shoppingBag': 'Shopping Bag',
      'emptyCart': 'Your cart is empty',
      'totalPayment': 'Total Payment',
      'checkout': 'Checkout',
      'proceedCheckout': 'Proceed to Checkout',
      'paymentMethod': 'Payment Method',
      'orderSummary': 'Order Summary',
      'totalItems': 'Total Items',
      'confirmPayment': 'Confirm Payment',
      'paymentSuccess': 'Payment Success',
      'orderSuccessful': 'Order Successful',
      'thankYou': 'Thank you for your purchase',
      'backHome': 'Back to Home',
      'clear': 'Clear',
      'noFavorite': 'No favorite items',
      'language': 'Language',
      'thai': 'ไทย',
      'english': 'English',
      'all': 'All',
      'electronics': 'Electronics',
      'jewelery': 'Jewelery',
      "men's clothing": "Men's Clothing",
      "women's clothing": "Women's Clothing",
    },
  };

  static String get(String key, String languageCode) {
    return _text[languageCode]?[key] ?? _text['en']?[key] ?? key;
  }

  static String category(String category, String languageCode) {
    final key = category.toLowerCase();

    if (key == 'all') {
      return get('all', languageCode);
    }

    return _text[languageCode]?[key] ?? category;
  }
}
